export const ORDER_STATUS_CONFIRMED="CONFIRMED";
export const ORDER_STATUS_Delivered="DELIVERED"
export const ORDER_STATUS_PENDING="PENDING"
export const ORDER_STATUS_CANCEL="CANCEL"
export const ORDER_STATUS_PROCESSING="PROCESSING"
